Merge 16.09 release
1. Merge 96boards/oe-rpb-manifest, branch: krogoth
   (commit: a2bb4d712946144a82d5b5cea3b802dbdbb2b9de)
2. Add 16.09.xml for OE RPB build
   https://builds.96boards.org/releases/reference-platform/openembedded/dragonboard410c/16.09/rpb/
3. Revise README
4. Remove 16.06.xml

diff --git a/setup-environment-internal b/setup-environment-internal
--- a/setup-environment-internal
+++ b/setup-environment-internal
@@ -18,6 +18,16 @@
 # with this program; if not, write to the Free Software Foundation, Inc.,
 # 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 #
+RPBcleanup() {
+        unset MACHINETABLE MACHLAYERS DISTROTABLE DISTROLAYERS DISTRO_DIRNAME OEROOT
+        unset ITEM MANIFESTS EULA EULA_MACHINE REPLY READ_EULA
+        unset usage oldmach
+
+        if [ -n "$BUILDDIR" ]; then
+                export BUILDDIR
+        fi
+}
+trap RPBcleanup RETURN
 
 if [ "$(whoami)" = "root" ]; then
     echo "ERROR: do not use the BSP as root. Exiting..."
@@ -74,11 +84,6 @@ Some of common targets are:
     core-image-minimal
 
 EOF
-
-unset MACHINETABLE MACHLAYERS DISTROTABLE DISTROLAYERS DISTRO_DIRNAME OEROOT
-unset ITEM MANIFESTS EULA EULA_MACHINE REPLY READ_EULA
-unset oldmach
-export BUILDDIR
 }
 
 # [Advantech] Check existed MACHINE & DISTRO
@@ -125,7 +130,7 @@ fi
 # Blacklist OE-core and meta-linaro, we only want 96boards + vendor layers
 DISTROLAYERS=$(find layers -print | grep "conf/distro/.*\.conf" | grep -v scripts | grep -v openembedded-core | grep -v meta-linaro | sed -e 's/\.conf//g' -e 's/layers\///' | awk -F'/conf/distro/' '{print $NF "(" $1 ")"}' | sort)
 
-if [ -z "${DISTRO}" ]; then
+if [ -n "${DISTROLAYERS}" ] && [ -z "${DISTRO}" ]; then
     # whiptail
     which whiptail > /dev/null 2>&1
     if [ $? -eq 0 ]; then
@@ -149,11 +154,11 @@ if [ -z "${DISTRO}" ]; then
             DISTRO=$(dialog --title "Available Distributions" --menu "Please choose a distribution" 0 0 20 $DISTROTABLE 3>&1 1>&2 2>&3)
         fi
     fi
+fi
 
-    # If nothing has been set, go for 'nodistro'
-    if [ -z "$DISTRO" ]; then
-        DISTRO="nodistro"
-    fi
+# If nothing has been set, go for 'nodistro'
+if [ -z "$DISTRO" ]; then
+    DISTRO="nodistro"
 fi
 
 # guard against Ctrl-D or cancel
@@ -191,6 +196,65 @@ export PATH=$(echo "$PATH" | awk -F: '{for (i=1;i<=NF;i++) { if ( !x[$i]++ ) pri
 # environment.
 export BB_ENV_EXTRAWHITE="MACHINE DISTRO TCLIBC TCMODE GIT_PROXY_COMMAND http_proxy ftp_proxy https_proxy all_proxy ALL_PROXY no_proxy SSH_AGENT_PID SSH_AUTH_SOCK BB_SRCREV_POLICY SDKMACHINE BB_NUMBER_THREADS"
 
+# Helper command for building images for mixed 32bit/64bit
+# ARM builds. The command allow to specify a secondary MACHINE
+# and image that will be built next to the primary target.
+# If no secondary image is specified the rpb-minimal-image image
+# will be built.
+
+
+bitbake_secondary_image () {
+    BITBAKE_OPTIONS=""
+    unset EXTRA_MACHINE
+    unset SECONDARY_IMAGE
+
+    SECONDARY_IMAGE='rpb-minimal-image'
+    while [[ $# -gt 1 ]]
+    do
+        key="$1"
+        case $key in
+            --extra-machine)
+            EXTRA_MACHINE="$2"
+            shift
+            ;;
+            --secondary-image)
+            SECONDARY_IMAGE="$2"
+            shift
+            ;;
+        *)
+            BITBAKE_OPTIONS=$BITBAKE_OPTIONS" "$1
+        ;;
+    esac
+    shift
+    done
+    BITBAKE_OPTIONS=$BITBAKE_OPTIONS" "$1
+    if [ -z "$EXTRA_MACHINE" ]
+    then
+        echo "   Error: you need to run $FUNCNAME with --extra-machine agument"
+        echo
+        echo "   Example:"
+        echo "     $ $FUNCNAME --extra-machine hikey rpb-weston-image"
+        return
+    fi
+
+    if [ "$EXTRA_MACHINE" == "$MACHINE" ]
+    then
+        echo "Error: the extra machine must be different from the machine you already set using setup-environment: "$MACHINE
+        return
+    fi
+
+    echo "Building first image. MACHINE:" $EXTRA_MACHINE " DISTRO:" $DISTRO
+
+    MACHINE=$EXTRA_MACHINE bitbake $SECONDARY_IMAGE
+
+    if [ $? != 0 ]; then
+        printf "Error building image"
+        return
+    fi
+    echo "Building second image. MACHINE:" $MACHINE " DISTRO:" $DISTRO
+
+    MACHINE=$MACHINE bitbake $BITBAKE_OPTIONS
+}
 mkdir -p "${BUILDDIR}"/conf && cd "${BUILDDIR}"
 if [ -f "conf/auto.conf" ]; then
     oldmach=$(egrep "^MACHINE" "conf/auto.conf" | sed -e 's%^MACHINE ?= %%' | sed -e 's/^"//'  -e 's/"$//')
@@ -249,7 +313,7 @@ fi
 # If the env variable EULA_$MACHINE is set it is used by default,
 # without prompting the user.
 # FIXME: there is a potential issue if the same $MACHINE is set in more than one layer.. but we should assert that earlier
-EULA=$(find ../layers -print | grep "conf/eula/$MACHINE" | grep -v scripts | grep -v openembedded-core | grep -v meta-linaro || true)
+EULA=$(find ../layers -path "*/conf/eula/$MACHINE" -print | grep -v scripts | grep -v openembedded-core | grep -v meta-linaro || true)
 
 if [ -n "$EULA" ]; then
 
